# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
    "iPhone 15 Pro Max", #6.7" Display
    "iPhone 14 Plus", #6.5" Display
    "iPhone SE (3rd generation)", #4.7" Display
    "iPad Pro (12.9-inch) (6th generation)",
    "iPad Pro (12.9-inch) (2nd generation)",
    "Apple Watch Ultra 2 (49mm)"
])

languages([
  "da", # Danish
  "de-DE", # German (Germany)
  "el", # Greek
  "en-GB", # English (United Kingdom)
  "en-US", # English (United States)
  "es-ES", # Spanish (Spain)
  "fi", # Finnish
  "fr-FR", # French (France)
  "it", # Italian
  "nl-NL", # Dutch (Netherlands)
  "no", # Norwegian
  "pt-PT", # Portuguese (Portugal)
  ["sv", "sv-SE"], # Swedish, Swedish (Sweden)
  "tr", # Turkish
])

# The name of the scheme which contains the UI Tests
scheme("Electricity Prices UI Tests")

# Where should the resulting screenshots be stored?
output_directory("./fastlane/screenshots")

configuration("Debug")
localize_simulator(true)
clear_previous_screenshots(false)
override_status_bar(false)
stop_after_first_error(true)
number_of_retries(0)
dark_mode(false)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
