# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
    "iPhone 15 Pro Max", #6.7" Display
    "iPad Pro 13-inch (M4)",
    "Apple Watch Ultra 2 (49mm)"
])

# TODO: Not sure if it's a good way to define locales consistently here, but feels like it. 
# - It's very confusing when mixing languages and locales.
# - If only specifying the language, `Locale.current.region` returns nil in the UI test.
# - Currently this does not generate the correct folder structure (as expected by deliver).
languages([
  "da-DK", # Denmark
  "de-DE", # Germany
  "el-GR", # Greece
  "en-GB", # United Kingdom
  "en-US", # United States
  "es-ES", # Spain
  "fi-FI", # Finland
  "fr-FR", # France
  "it-IT", # Italy
  "nl-NL", # Netherlands
  "nb-NO", # Norway
  "pt-PT", # Portugal
  "sv-SE", # Sweden
  "tr-TR", # Turkey
])

# The name of the scheme which contains the UI Tests
scheme("Electricity Prices UI Tests")

# Where should the resulting screenshots be stored?
output_directory("./fastlane/screenshots")

configuration("Debug")
localize_simulator(true)
clear_previous_screenshots(false)
override_status_bar(true)
stop_after_first_error(false)
number_of_retries(2)
dark_mode(false)
derived_data_path('./DerivedData')
headless(false)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
