# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
    "iPhone 15 Pro Max", #6.7" Display
    # "iPhone 14 Plus", #6.5" Display
    # "iPhone 8 Plus", #5.5" Display
    # "iPhone SE (3rd generation)", #4.7" Display
    # "iPad Pro (12.9-inch) (6th generation)",
    # "iPad Pro (12.9-inch) (2nd generation)",
    # "Apple Watch Ultra 2 (49mm)"
])

languages([
  "en-US",
  # ["sv", "sv-SE"],
])

# The name of the scheme which contains the UI Tests
scheme("Electricity Prices UI Tests")

# Where should the resulting screenshots be stored?
output_directory("./fastlane/screenshots")

clear_previous_screenshots(true)
override_status_bar(true)
stop_after_first_error(true)
dark_mode(false)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
